# Generated by Django 5.0.4 on 2024-04-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_user_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
