# Generated by Django 5.0.4 on 2024-04-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_ticket_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(help_text='Número de asiento', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.seat'),
        ),
    ]
