# Generated by Django 5.0.4 on 2024-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_seat_seat_number_alter_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(help_text='Número de asiento', max_length=5),
        ),
    ]
