# Generated by Django 5.0.4 on 2024-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_seat_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(help_text='Número de asiento', max_length=10),
        ),
    ]
