# Generated by Django 5.0.4 on 2024-04-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_ticket_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='mobile',
            new_name='fare',
        ),
    ]
